[project]
name = "transformer-translation"
version = "0.1.0"
description = "German to English Transformer project"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "datasets>=5.0.1",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "sacrebleu>=2.6.0",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]
